### ISSUE TITLE
Oprava úkolu

### ISSUE THREAD

**Issue by jakubledl** [ICerv/domaci_zadani_1#1]
Ahoj!

Fakt skvělá práce, splněno :-) Měl bych jen pár poznámek:

- ve funkci `filterApi` teoreticky není potřeba získávat checkbox vždycky pomocí `querySelector`; funkce může mít parameter `event` a checkbox pak najdeme v `event.target` (a jsou i jiné možnosti). Ale ničemu to nevadí :-)
- jak `if`, tak `else` ve `filterApi` jsou dost podobné, liší se jen v adrese (a i ta je dost podobná). Nešlo by to vyřešit podobně, jako tu fajfku v komponentě `Task`, nebo třeba pomocí [ternárního operátoru](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator)?

**Comment by ICerv** [comment]
Ahoj Jakube,
dekuji Ti za feedback. Rada bych to opravila, ale kdyz jsem si otevrela v prohlizici svuj jeste neopraveny kod, tak se mi prestal vubec zobrazovat, pritom pred odevzdanim mi fungoval. A zatim nemuzu na to prijit:(. Nemuze to byt tim, ze se neco zmenilo v API dokumentaci?

**Comment by ICerv** [comment]
Ufff, tak problem jsem vyresila a kod opravila:
-funkci addEventListener zkratila pomoci ternarniho operatoru a pouzila parameter(e)
- funkci renderTasks taky trochu zkratila
Bohuzel, vznikl mi ale dalsi problem, tentokrat s gitem:)), takze opravu posilam zatim takto(viz.nize)
_____________________________________________________________________________________________________________
import { Task } from "./Task/index.js";

const renderTasks = (tasks) => {
  document.querySelector('.todo__tasks').innerHTML = tasks
    .map((task) => Task(task))
    .join('');
};

fetch('https://apps.kodim.cz/daweb/trening-api/apis/tasks-api/tasks')
  .then((response) => response.json())
  .then(renderTasks);

document.getElementById('checkbox-undone').addEventListener("change", (e) => {
  fetch(`https://apps.kodim.cz/daweb/trening-api/apis/tasks-api/tasks${e.target.checked ? "?done=false" : ""}`)
    .then((response) => response.json())
    .then(renderTasks);
})

**Comment by jakubledl** [comment]
Ahoj, přesně tak jsem to myslel 👍 Díky moc ještě za tuhle opravu nad rámec úkolu 🥇
